[server]
host = "0.0.0.0"
port = 18080

[hdfs]
namenode_url = "hdfs://localhost:8020"
connection_timeout_ms = 30000
read_timeout_ms = 60000

[history]
log_directory = "/spark-events"
database_directory = "./data/hdfs"
update_interval_seconds = 30
compression_enabled = true