[server]
host = "0.0.0.0"
port = 18080

[s3]
bucket_name = "spark-events"
region = "us-east-1"
endpoint_url = "http://localhost:9000"
access_key_id = "minioadmin"
secret_access_key = "minioadmin123"
connection_timeout_ms = 30000
read_timeout_ms = 60000

[history]
database_directory = "./data/s3"
update_interval_seconds = 30
compression_enabled = true